model_name: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
data_path: data/collection/deepseek_llama_8b/math_open.json
prompt_index: 6
reward_type: correctness
objective: reward_gap
masking_algorithm: nodewise_activation_patching_kv_cache
num_new_branches: 16
mask_granularity: pair
mask_mode: prefix
layers_to_analyse: all
max_sampling_tokens: 10000
analysis_timestep: 1416
sentence_gap: 4
output_dir: results/circuit_discovery
file_name: reward_with_importance_sampling_at_1416_16_branches_kv_cache
ablate_non_target_layers: true
device: cuda:0
